export const GET_FEMALE_USER_REQUEST = "GET_FEMALE_USER_REQUEST";
export const GET_FEMALE_USER_SUCCESS = "GET_FEMALE_USER_SUCCESS";
export const GET_FEMALE_USER_FAILURE = "GET_FEMALE_USER_FAILURE";
