export const ActionTypes = {
  FETCH_USERS: "FETCH_USERS",
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE"
  // SET_PRODUCTS: "SET_PRODUCTS",
  // SELECT_PRODUCTS: "SELECT_PRODUCTS",
  // REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
